### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by jgmarquesm** [jgmarquesm/Linketinder#1]
# Requisitos Obrigatórios: 

- [x] **Manter um Array de candidatos com no mínimo 5 candidatos cadastrados.**

- [x] **Para cada candidato, tem que ser possível salvar informações: Nome, E-mail, CPF, idade, Estado, CEP e descrição pessoal.**

- [x] **Cada candidato tem um atributo de competências, que também é um Array.**

- [x] **Deve existir um Array de empresas com no mínimo 5 empresas.**

- [x] **Para cada empresa, tem que ser possível salvar informações: Nome, E-mail Corporativo, CNPJ, País, Estado, CEP e Descrição da empresa.**

- [x] **A empresa também tem um atributo de competências, que se refere ao que a empresa espera dos candidatos.**

- [x] **Ser possível listar todas empresas e todos os candidatos.**

# Requisitos Opcionais:

- [x] **Ser possível fazer o cadastro de novos candidatos ou empresas.**
